### ISSUE TITLE
Terminal command error for both versions after 0.2.0

### ISSUE THREAD

**Issue by IntoComatose** [Major-Scott/TerminalPlus#1]
Hi! First off I'm loving this mod. However, I seem to encounter an issue when entering "moons" into the Terminal for every version after 0.2.0

This is the error I receive in the cmd window the second I try to send 'moons'

[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
TerminalPlus.Nodes.MoonsPage () (at <2d85965c653f4f40b949ecbb28eb9380>:IL_01FB)
TerminalPlus.TerminalPatches.TerminalEventPrefix (TerminalNode node, Terminal __instance) (at <2d85965c653f4f40b949ecbb28eb9380>:IL_03EA)
(wrapper dynamic-method) Terminal.DMD<Terminal::RunTerminalEvents>(Terminal,TerminalNode)
Terminal.LoadNewNode (TerminalNode node) (at <af9b1eec498a45aebd42601d6ab85015>:IL_0007)
(wrapper dynamic-method) Terminal.DMD<Terminal::OnSubmit>(Terminal)
UnityEngine.Events.InvokableCall.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0010)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <e27997765c1848b09d8073e5d642717a>:IL_0049)
TMPro.TMP_InputField.SendOnEndEdit () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_000E)
TMPro.TMP_InputField.ReleaseSelection () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_001B)
TMPro.TMP_InputField.DeactivateInputField (System.Boolean clearSelection) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_00B0)
TMPro.TMP_InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_007C)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <17de86d66286445fa95af59fa8fa644d>:IL_0000)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <17de86d66286445fa95af59fa8fa644d>:IL_0067)
UnityEngine.EventSystems.EventSystem:Update()

Is this possibly from a conflict with another mod installed after one of your updates or is this from the update itself?

Thanks!

**Comment by Major-Scott** [comment]
> Hi! First off I'm loving this mod. However, I seem to encounter an issue when entering "moons" into the Terminal for every version after 0.2.0
> 
> This is the error I receive in the cmd window the second I try to send 'moons'
> 
> [Error : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array. Stack trace: TerminalPlus.Nodes.MoonsPage () (at <2d85965c653f4f40b949ecbb28eb9380>:IL_01FB) TerminalPlus.TerminalPatches.TerminalEventPrefix (TerminalNode node, Terminal __instance) (at <2d85965c653f4f40b949ecbb28eb9380>:IL_03EA) (wrapper dynamic-method) Terminal.DMDTerminal::RunTerminalEvents(Terminal,TerminalNode) Terminal.LoadNewNode (TerminalNode node) (at :IL_0007) (wrapper dynamic-method) Terminal.DMDTerminal::OnSubmit(Terminal) UnityEngine.Events.InvokableCall.Invoke () (at :IL_0010) UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <e27997765c1848b09d8073e5d642717a>:IL_0049) TMPro.TMP_InputField.SendOnEndEdit () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_000E) TMPro.TMP_InputField.ReleaseSelection () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_001B) TMPro.TMP_InputField.DeactivateInputField (System.Boolean clearSelection) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_00B0) TMPro.TMP_InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_007C) UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <17de86d66286445fa95af59fa8fa644d>:IL_0000) UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <17de86d66286445fa95af59fa8fa644d>:IL_0067) UnityEngine.EventSystems.EventSystem:Update()
> 
> Is this possibly from a conflict with another mod installed after one of your updates or is this from the update itself?
> 
> Thanks!

Hi! Sorry for the delay, I had finals this last week. I can't see what the problem is off the top of my head, but my guess is that my mod isn't recognizing the full list of moons; could you send me a list of the mods you were using? I recognize the error type and will try to fix it with this next update :)

**Comment by IntoComatose** [comment]
Sure thing! Was rather surprised to see the error suddenly pop up after an update. Here are the moons;

- Big Boos Haunt Moon (https://thunderstore.io/c/lethal-company/p/PanMan/Big_Boos_Haunt_Moon/)
- BikiniBottom (https://thunderstore.io/c/lethal-company/p/G7Exid/BikiniBottom/)
- Ether (https://thunderstore.io/c/lethal-company/p/LethalMoonTeam/Ether/)
- Generic Moons (https://thunderstore.io/c/lethal-company/p/Generic_GMD/Generic_Moons/)
- LethalCenterHospitalMap (https://thunderstore.io/c/lethal-company/p/Kimukirano/LethalCenterHospitalMap/)
- Luigis Mansion (https://thunderstore.io/c/lethal-company/p/PanMan/Luigis_Mansion_Moon/)
- SR Marooners Bay (https://thunderstore.io/c/lethal-company/p/FissionMetroid101/SR_Marooners_Bay/)
- Wesleys Moons (https://thunderstore.io/c/lethal-company/p/Magic_Wesley/Wesleys_Moons/)
- Zelda Moons (https://thunderstore.io/c/lethal-company/p/Dafini/Zelda_Moons/)


Thanks for the help! Really enjoy the organization in your mod.

**Comment by Major-Scott** [comment]
Thanks! One last thing, were you using this exact list before 0.2.0? That'll help me narrow down whether it's an incompatibility problem or just a bug from the mod

**Comment by IntoComatose** [comment]
I believe Big Boos, SR Marooners Bay, and possibly Zelda Moons / BikiniBottom were not included at first, but I added them after receiving the error and downgrading back to 0.2.0.

**Comment by IntoComatose** [comment]
The newest update allows everything to work properly. Thank you very much for your hard work!
