### ISSUE TITLE
Incorrect weather on the terminal

### ISSUE THREAD

**Issue by kellianoy** [Major-Scott/TerminalPlus#2]
Hi! Thanks for the mod. I've been having some trouble with it, unfortunately.

## Conditions

Multiplayer, Modded (mainly moon additions)
My friends have exactly the same configurations and mods as I do

## Description of the issue

When selecting a planet in Multiplayer with apparently no weather on the terminal, the screen resume of the map show a different weather. The actual weather on the planet is the one on the screen.

Could this be caused by a lack of configuration sharing or seed sharing?

**Comment by Major-Scott** [comment]
> Hi! Thanks for the mod. I've been having some trouble with it, unfortunately.
> 
> ## Conditions
> Multiplayer, Modded (mainly moon additions) My friends have exactly the same configurations and mods as I do
> 
> ## Description of the issue
> When selecting a planet in Multiplayer with apparently no weather on the terminal, the screen resume of the map show a different weather. The actual weather on the planet is the one on the screen.
> 
> Could this be caused by a lack of configuration sharing or seed sharing?

Hi! Sorry for the delay, I had finals. I noticed this too when playing with friends for the first time yesterday and am almost positive I know what the problem is. I'll fix it for the next update which should hopefully come out tonight :)

**Comment by kellianoy** [comment]
> > Hi! Thanks for the mod. I've been having some trouble with it, unfortunately.
> > ## Conditions
> > Multiplayer, Modded (mainly moon additions) My friends have exactly the same configurations and mods as I do
> > ## Description of the issue
> > When selecting a planet in Multiplayer with apparently no weather on the terminal, the screen resume of the map show a different weather. The actual weather on the planet is the one on the screen.
> > Could this be caused by a lack of configuration sharing or seed sharing?
> 
> Hi! Sorry for the delay, I had finals. I noticed this too when playing with friends for the first time yesterday and am almost positive I know what the problem is. I'll fix it for the next update which should hopefully come out tonight :)

Best of luck for your finals! I know how tough it can be.
I'd like to add that the desynchronization happens only after the first run, that might help uncover why it doesn't refresh itself.

Furthermore, I've noticed that with the mod RandomRoutes, the entries on the monitor are duplicated. I don't know if it is relevant or not, but I thought I'd mention it.

**Comment by Major-Scott** [comment]
> > > Hi! Thanks for the mod. I've been having some trouble with it, unfortunately.
> > > ## Conditions
> > > Multiplayer, Modded (mainly moon additions) My friends have exactly the same configurations and mods as I do
> > > ## Description of the issue
> > > When selecting a planet in Multiplayer with apparently no weather on the terminal, the screen resume of the map show a different weather. The actual weather on the planet is the one on the screen.
> > > Could this be caused by a lack of configuration sharing or seed sharing?
> > 
> > 
> > Hi! Sorry for the delay, I had finals. I noticed this too when playing with friends for the first time yesterday and am almost positive I know what the problem is. I'll fix it for the next update which should hopefully come out tonight :)
> 
> Best of luck for your finals! I know how tough it can be. I'd like to add that the desynchronization happens only after the first run, that might help uncover why it doesn't refresh itself.
> 
> Furthermore, I've noticed that with the mod RandomRoutes, the entries on the monitor are duplicated. I don't know if it is relevant or not, but I thought I'd mention it.

Thanks! Last one was Friday so now I just have to wait, fingers crossed! Also that luckily confirms that the weather problem was exactly what I thought it was; in the last update, I added a setting for weather names that are too long to fit, but forgot to have them update each day instead of each session. For RandomRoutes, is it just my mod you've noticed it with? I've found a couple of different problems that causes the duplicates but only one is coming from terminalplus, so I just kind of have to hide the ones caused by other mods XD

**Comment by kellianoy** [comment]
> > > > Hi! Thanks for the mod. I've been having some trouble with it, unfortunately.
> > > > ## Conditions
> > > > Multiplayer, Modded (mainly moon additions) My friends have exactly the same configurations and mods as I do
> > > > ## Description of the issue
> > > > When selecting a planet in Multiplayer with apparently no weather on the terminal, the screen resume of the map show a different weather. The actual weather on the planet is the one on the screen.
> > > > Could this be caused by a lack of configuration sharing or seed sharing?
> > > 
> > > 
> > > Hi! Sorry for the delay, I had finals. I noticed this too when playing with friends for the first time yesterday and am almost positive I know what the problem is. I'll fix it for the next update which should hopefully come out tonight :)
> > 
> > 
> > Best of luck for your finals! I know how tough it can be. I'd like to add that the desynchronization happens only after the first run, that might help uncover why it doesn't refresh itself.
> > Furthermore, I've noticed that with the mod RandomRoutes, the entries on the monitor are duplicated. I don't know if it is relevant or not, but I thought I'd mention it.
> 
> Thanks! Last one was Friday so now I just have to wait, fingers crossed! Also that luckily confirms that the weather problem was exactly what I thought it was; in the last update, I added a setting for weather names that are too long to fit, but forgot to have them update each day instead of each session. For RandomRoutes, is it just my mod you've noticed it with? I've found a couple of different problems that causes the duplicates but only one is coming from terminalplus, so I just kind of have to hide the ones caused by other mods XD

I don't think I've noticed it with any other mods that I'm using, only specifically with RandomRoutes.
Happy that you can fix everything!

I hope you will get good grades haha, what are you majoring in?
